/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include<led.h>
#include<FreeRTOS.h>
#include<FreeRTOSConfig.h>
#include<task.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vAperiodicLEDBlinkingTask(void *pvParam)
{
	while(1){
		led_toggle(LED_GREEN);
		vTaskDelay(1000 / portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}

void vPeriodicLEDBlinkingTask(void *pvParam)
{
	portTickType pxPreviousWakeUpTime = xTaskGetTickCount();
	while(1){
		led_toggle(LED_RED);
		vTaskDelayUntil(&pxPreviousWakeUpTime, 3000 / portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}

int main(void)
{
	led_init(LED_GREEN);
	led_init(LED_RED);

	xTaskCreate(vAperiodicLEDBlinkingTask, "Task1", configMINIMAL_STACK_SIZE, NULL, 4, NULL);
	xTaskCreate(vPeriodicLEDBlinkingTask, "Task2", configMINIMAL_STACK_SIZE, NULL, 4, NULL);

	vTaskStartScheduler();

	while(1);

}

